### PR TITLE
Feature  repo list layout

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by jeffworley** [comment]
Solid work as usual _CMD (Classmate Dave)_ :+1:

**Comment by karjac14** [comment]
Great work! :+1:

**Comment by ShayHall** [comment]
Looks good.  Why did you use `<a>` tags? :+1:

**Comment by s4dmw** [comment]
@ShayHall - used `<a>` tags as placeholders for the links to get the sorted repo lists

**Pull request merged**
